### ISSUE TITLE
Faute d'orthographe sur page d'accueil de memoire.cloud

### ISSUE THREAD

**Issue by CorentinSol** [memoire-app/memoire-app#42]
Bonjour,

Une faute d'orthographe s'est glissée sur la page d'accueil du site dans la rubrique [Contact](https://memoire.cloud/#contact): dans "pleins d'autres choses" (voir capture d'écran), "plein" ne prend pas de 's'. Confirmation de la règle sur [ce site](https://www.question-orthographe.fr/question/accord-de-pleins-dautres-chose/) par exemple.

PS: n'étant pas encore familier avec les contributions open-source, n'hésitez pas à m'indiquer où adresser mes remarques si ce n'est pas le bon endroit.

![Screenshot_2024-09-23-12-25-38-906_com android chrome-edit](https://github.com/user-attachments/assets/6a99ab0f-e9f4-49d0-aa44-a5fec607ead4)

**Comment by RemiSaurel** [comment]
Hello, c'est super merci pour les issues !
Non c'est parfait, je fix ça desuite :)

**Comment by RemiSaurel** [comment]
C'est fix, ça partira sur une version de fix qui pourrait régler des bugs + problématiques
