### ISSUE TITLE
Remarques concernant la responsivité du site (Smartphone)

### ISSUE THREAD

**Issue by CorentinSol** [memoire-app/memoire-app#43]
Bonjour,

J'ai constaté deux éléments qui me semblent pouvoir faire l'objet de discussions concernant la prise en charge du [site](https://memoire.cloud/) pour smartphones:

Premièrement, les questions de la partie "Questions fréquentes" sont coupées dans l'affichage (voir premier screenshot). En tant qu'utilisateur (et il ne s'agit là que de mon avis), je préfèrerais qu'elles soient entièrement affichées sur plusieurs lignes, plutôt que de voir uniquement le début de la question suivi de "...". 
Par exemple, la question "Mes decks sont-ils accessibles par t..." serait remplacée par la question complète mais affichée sur deux ou trois lignes.

Deuxièmement, le screenshot de l'IHM de l'application sur la page d'accueil me semble perdre son contexte lors de la consultation du site sur smartphone (voir second screenshot). Peut-être que le situer au même endroit que sur la version "grand écran", c'est-à-dire juste après le bouton "créer un deck" et juste avant la partie "Pourquoi utiliser memoire" permettrait de garder le contexte ?
Dans les deux cas, je me demande si une bordure, une ombre ou autre solution technique ne permettrait pas de rendre plus explicite le fait qu'il s'agisse d'une capture d'écran, car la capture est blanche, et le fond de la page d'accueil aussi, donc la démarcation me semble peut-être insuffisante ?

![Screenshot_2024-09-23-12-25-07-380_com android chrome-edit](https://github.com/user-attachments/assets/2f6acf76-c6e7-4ffa-ae0c-c9b20ab0f593)

![Screenshot_2024-09-23-12-26-02-266_com android chrome-edit](https://github.com/user-attachments/assets/ccdf68b5-e78c-4f43-84f0-817738ffa15b)

**Comment by RemiSaurel** [comment]
Pour les questions, je suis d'accord, voilà le fix prévu : 

![image.png](https://uploads.linear.app/455a81e3-0b2a-4aaa-b702-853c7ca3a4fd/9eb84e8d-a0f3-453b-aec6-f770364b5c2e/538d9d9e-65d2-42df-981c-8ca3f296f52c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ1NWE4MWUzLTBiMmEtNGFhYS1iNzAyLTg1M2M3Y2EzYTRmZC85ZWI4NGU4ZC1hMGYzLTQ1M2ItYWVjNi1mNzcwMzY0YjVjMmUvNTM4ZDlkOWUtNjVkMi00MmRmLTk4MWMtOGNhM2YyOTZmNTJjIiwiaWF0IjoxNzI3MDkyOTA5LCJleHAiOjMzMjk3NjUyOTA5fQ.DzL3WUhOinsblVrs9tj3SuKIaFUQUuHTra1U9d3912s "=239x")

Pour le screenshot, sur mobile j'ai enlevé le premier screen car trop petit par rapport au format. Je trouve que le screenshot est bien placé car l'utilisateur est "guidé" avec le 1 -> 2 -> 3 -> 4. Par contre, il faudrait bien le démarquer. Peut-être qu'une vidéo en autoplay ou un GIF serait mieux.

**Comment by CorentinSol** [comment]
Le fix prévu me semble très bien.

Je comprends mieux l'utilité du screenshot avec votre retour, et dans ce cas, je pense qu'effectivement une vidéo/GIF serait très explicite. Elle permettrait également de donner une "utilité" aux barres de chargement (présentes sur la version grand écran) situées dans les cartes 1-2-3-4 de "pourquoi utiliser memoire". En l'état actuel je ne comprenais pas bien l'utilité de celles-ci.

**Comment by RemiSaurel** [comment]
Fixed in https://github.com/memoire-app/memoire-app/pull/49
