### ISSUE TITLE
Moyens de connexion

### ISSUE THREAD

**Issue by CorentinSol** [memoire-app/memoire-app#45]
Re-bonjour,

Je constate que la seule manière de se connecter à l'application est de passer par le compte d'un autre service.
L'implémentation d'une solution pour créer un compte uniquement dédié à l'application est-elle prévue ? Passer par un service tiers peut être rebutant pour certains utilisateurs.

**Comment by RemiSaurel** [comment]
Yes, la création d'un compte via email / password classique est faisable. J'avais pas vraiment de visibilité si le fait de proposer des auth via services tiers allait "bloquer" des utilisateurs. En fonction des retours sur cette alpha, la solution sera développée 🙂
