### ISSUE TITLE
Tag non attribué ni lors de la création du deck, ni après modification

### ISSUE THREAD

**Issue by CorentinSol** [memoire-app/memoire-app#46]
Re-bonjour,

Lors de la création d'un deck, il semblerait que les tags ne soient pas affectés à celui-ci (ou simplement pas affichés ?). De même, lors de la modification des tags, aucun ne semble s'ajouter/se modifier puisque l'état affiché reste le même.

Ci-joint des screenshots pour reproduire le bug (si cela peut jouer, le compte utilisé est lié à Discord).

Étape 1: Création du deck avec un tag
![image](https://github.com/user-attachments/assets/ef2b9b92-1ae2-4d28-9392-d9b379e47cd8)

Étape 2: Affichage dans l'onglet deck ne semble pas indiquer les tags
![image](https://github.com/user-attachments/assets/86dfb49a-31c4-4b58-be27-5b186a039295)

Étape 3: Affichage des flashcards dans le deck ne semble pas afficher de tag
![image](https://github.com/user-attachments/assets/28a94526-35f0-4b89-9cd7-063718ba6925)

Étape 4: Modification des tags du deck
![image](https://github.com/user-attachments/assets/759f64a3-1e80-4c67-97d3-d24876dadfa5)

Étape 5: Infobulle présente malgré l'absence "visible" de modification
![image](https://github.com/user-attachments/assets/74f9b719-474f-4c25-9077-445d94968e28)

**Comment by CorentinSol** [comment]
En effet, cela fonctionne en appuyant sur "Entrée". 
Dans ce cas une aide semble utile oui, ou sinon envisager un traitement du champ lorsque l'utilisateur appuie sur le bouton "enregistrer" (pour enregistrer le deck), mais dans ce cas spécifier le séparateur à utiliser ?

**Comment by RemiSaurel** [comment]
Je pense que l'aide "Entrée pour ajouter un deck" suffira, je veux pas surcharger l'interface en acceptant un séparateur.
