### ISSUE TITLE
Confidentialité du créateur d'un deck publique

### ISSUE THREAD

**Issue by CorentinSol** [memoire-app/memoire-app#47]
Re-bonjour,

Lorsqu'un utilisateur rend un deck publique, son pseudo est affiché (voir l'emplacement sur le screenshot). Dans le cas d'un utilisateur loggé avec un compte Discord, c'est son identifiant qui est affiché. Peut-être faudrait-il proposer le choix d'un pseudo à afficher plutôt que de diffuser l'identifiant que l'utilisateur souhaite peut-être (probablement ?) garder privé ?

Il faudrait dans ce cas tester si cette problématique est commune à chaque moyen de connexion, mais également si le créateur du deck est affiché lors du partage d'un deck (même privé). 
Un exemple pour ce deuxième cas: 
- userA partage un deck privé à userB => userB voit-il l'identifiant Discord de l'userA ?
- userB partage ensuite à userC ce même deck => userC voit-il l'identifiant Discord de userA et/ou de userB ?

![image](https://github.com/user-attachments/assets/e82c8732-57a6-40d9-a7e2-936d95beb269)

**Comment by RemiSaurel** [comment]
Je vais catégoriser l'issue en `Pending`. Je ne suis pas sûr que le choix d'un pseudo pour le partage soit une solution viable (fausses identités, impossible de chercher des decks par auteurs "facilement"). Comme pour l'auth avec l'email / password, on va voir si cette problématique ressort.

Lorsqu'on partage / importe un deck (public ou privé), il est directement copié dans le compte de l'utilisateur. Pour le moment, il n'y a pas d'infos affichés, mais je peux retrouver le créateur original. C'est d'ailleurs ce qui va être ajouté à la page explore : pour le moment, je ne remonte que d'un cran pour avoir l'auteur. Je vais remonter de manière récursive jusqu'à l'auteur original pour afficher son pseudo.
