### ISSUE TITLE
Remarques/Suggestions IHM Révision

### ISSUE THREAD

**Issue by CorentinSol** [memoire-app/memoire-app#48]
Voici quelques remarques concernant l'IHM en mode révision d'un deck:

- Peut-être qu'une indication dans la case "A revoir" indiquant que la carte sera re présentée **dans la même session de révision** (et donc qu'il ne s'agit pas "simplement" d'un classement comme les autres) rendrait plus claire l'utilisation. Par exemple, il pourrait être indiquée dans le bouton "A revoir": "La carte sera rejouée dans cette même session de révision" ?

- le bouton "voir la réponse" ne me semble pas bien placé puisqu'il est situé à droite de la question, et de petite taille. Aussi, il se démarque peu du fond. Le placer en-dessous de la question pourrait peut-être rendre l'IHM plus lisible ? 

- concernant les boutons d'évaluation, ne faudrait-il pas les faire apparaître après avoir affiché la réponse lorsqu'il ne s'agit pas du mode de révision "examen" ? Cela peut éventuellement rejoindre le point précédent, puisque le bouton "voir la réponse" se situerai dans ce cas sous la carte, et une fois cliqué, les boutons d'évaluation le remplacerait (avec éventuellement au centre de ces boutons un nouveau bouton "revoir la question") ? J'ajoute deux croquis pour illustrer mes propos

Croquis 1: les boutons d'évaluation ne sont pas visibles tant que l'user n'a pas consulté la réponse, et le bouton pour consulter la réponse se trouve sous la carte
![IMG_20240923_144933](https://github.com/user-attachments/assets/8f759e90-ba64-4553-8517-595dcce08178)

Croquis 2: les boutons d'évaluation sont affichés une fois que l'user a consulté la réponse pour la première fois. Ensuite, il peut alterner entre afficher la question ou la réponse à l'aide du bouton situé au centre des 4 boutons d'évaluation
![IMG_20240923_145337](https://github.com/user-attachments/assets/8f0121df-9257-4dd9-9482-cde0ccca5e71)

**Comment by RemiSaurel** [comment]
> * Peut-être qu'une indication dans la case "A revoir" indiquant que la carte sera re présentée **dans la même session de révision** (et donc qu'il ne s'agit pas "simplement" d'un classement comme les autres) rendrait plus claire l'utilisation. Par exemple, il pourrait être indiquée dans le bouton "A revoir": "La carte sera rejouée dans cette même session de révision" ?

Tout à fait d'accord pour ajouter une indication sur le comportement des révisions. Je vais rajouter une icone qui ouvrira une `Modal` ici.

<img src="https://uploads.linear.app/455a81e3-0b2a-4aaa-b702-853c7ca3a4fd/732cf7f7-a520-4f22-9571-6630ce3638cd/10551bc0-fbad-44a7-bc71-3b60d6209fca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ1NWE4MWUzLTBiMmEtNGFhYS1iNzAyLTg1M2M3Y2EzYTRmZC83MzJjZjdmNy1hNTIwLTRmMjItOTU3MS02NjMwY2UzNjM4Y2QvMTA1NTFiYzAtZmJhZC00NGE3LWJjNzEtM2I2MGQ2MjA5ZmNhIiwiaWF0IjoxNzI3MTAyNDM4LCJleHAiOjMzMjk3NjYyNDM4fQ.Kadn5V8ENdhy-LjfJPhs7-O5e1XkIjtQtxgFDrkQlNI " alt="CleanShot 2024-09-23 at 16.37.04.png" width="948" height="131" />

> * le bouton "voir la réponse" ne me semble pas bien placé puisqu'il est situé à droite de la question, et de petite taille. Aussi, il se démarque peu du fond. Le placer en-dessous de la question pourrait peut-être rendre l'IHM plus lisible ?

Oui, je l'avais placé à droite pour "simuler" le fait de "retourner la carte" comme l'on retourne une page. Mais c'est sûrement mieux de l'avoir en-dessous, comme sur du mobile.

> * concernant les boutons d'évaluation, ne faudrait-il pas les faire apparaître après avoir affiché la réponse lorsqu'il ne s'agit pas du mode de révision "examen" ? 

Je ne veux pas forcer les utilisateurs à devoir consulter la réponse pour pouvoir s'autoévaluer. Avoir un mode ou un paramètrage qui forcerait ça est envisageable, mais le fonctionnement par défaut doit rester tel quel.

**Comment by RemiSaurel** [comment]
![CleanShot 2024-09-23 at 18.19.28@2x.png](https://uploads.linear.app/455a81e3-0b2a-4aaa-b702-853c7ca3a4fd/91aa0836-3d8c-45ba-94e2-e1c306f8b058/68c8cf39-4421-4ab4-8d1e-b7ed82157a2c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ1NWE4MWUzLTBiMmEtNGFhYS1iNzAyLTg1M2M3Y2EzYTRmZC85MWFhMDgzNi0zZDhjLTQ1YmEtOTRlMi1lMWMzMDZmOGIwNTgvNjhjOGNmMzktNDQyMS00YWI0LThkMWUtYjdlZDgyMTU3YTJjIiwiaWF0IjoxNzI3MTA4MzkxLCJleHAiOjMzMjk3NjY4MzkxfQ.FIPdqqOiYyN7BpdR-knD4emDTdsH26Ldw7EHfdEGupE "=453x")

Fix proposé pour la Modal d'aide.
